vm: fix unused result warning
When building against glibc with enabled source fortification, gcc reports
the following issue:

    .../vm.c: In function ‘uc_vm_signal_raise’:
    .../vm.c:3161:9: error: ignoring return value of ‘write’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
     3161 |         write(vm->signal.sigpipe[1], &signum, sizeof(signum));
          |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Since we cannot do any meaningful handling of a potential write error in
the affected signal handler context, simply solve this issue by wrapping
the `write()` call into an empty `if ()` statement.

Signed-off-by: Jo-Philipp Wich <jo@mein.io>